
name: ci cd new

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag in env
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sanu139/app:${{ env.TAG }}
 deploynodeapp:
    needs: [docker]
    runs-on: self-hosted
    steps:
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: "sanu139/app:*"
          replace: "sanu139/app:${{ env.TAG }}"
          include: "/home/anu/wordpress/node.yml"
          regex: true
    - name: running 
      run: |
          cd /home/anu/wordpress
          ls
          kubectl apply -f node.yml
