name: ci cd new

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
 develop-dev:
    needs: [docker] 
    runs-on: self-hosted
    if: contains('refs/heads/develop',github.ref)
    steps:
    - name: Set tag in env
      run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
    - name: running 
      run: |
          cd /home/anu/dev
          sed -i "34d" node.yml
          sed -i "/containers:/a \ \ \ \ \ \ - image:\ sanu139/app:${{ env.TAG }}" node.yml
          kubectl apply -f node.yml  
 docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag in env
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sanu139/app:${{ env.TAG }}
 deploy-prod:
    needs: [docker]
    runs-on: self-hosted
    if: contains('refs/heads/master',github.ref)
    steps:
    - name: Set tag in env
      run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
    - name: running 
      run: |
          cd /home/anu/wordpress
          sed -i "34d" node.yml
          sed -i "/containers:/a \ \ \ \ \ \ - image:\ sanu139/app:${{ env.TAG }}" node.yml
          kubectl apply -f node.yml
