
name: ci cd

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          tags: sanu139/app:${{ env.COMMIT_SHA }}

 deploynodeapp:
    needs: [docker]
    runs-on: self-hosted
    steps:
    - name: running 
      run: |
          cd /home/anu/wordpress
          run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          sed -i 's/image: sanu139/app:*/image: sanu139/app:${{ env.COMMIT_SHA }}/g' ./node.yaml
          kubectl apply -f node.yml
